name: My name is David Shawe and I'm a designer from Northern Ireland.
markdown: kramdown
highlighter: rouge # or rouge or null
baseurl:
url: http://shawe.co
sass:
  sass_dir: css
exclude:
  [
    "node_modules",
    "gulpfile.js",
    "package.json",
    "src",
    "Gemfile",
    "Gemfile.lock",
  ]
